max_rank: 4
sweeps_number: 2
maxvol_threshold: 1e-5
task_config:
  x0: [0, 1]
  x1: [0, 1]
  x2: [0, 1]
  x3: [0, 1]
  x4: [0, 1]
  x5: [0, 1]
  x6: [0, 1]
  x7: [0, 1]
  x8: [0, 1]
  x9: [0, 1]
  x10: [0, 1]
  x11: [0, 1]
  x12: [0, 1]
  x13: [0, 1]
  x14: [0, 1]
  x15: [0, 1]
  x16: [0, 1]
  x17: [0, 1]
  x18: [0, 1]
  x19: [0, 1]