max_rank: 5
sweeps_number: 2
maxvol_threshold: 1e-5
task_config:
  "0": ["h", "s", "t", "cnot", "id"]
  "1": ["h", "s", "t", "cnot", "id"]
  "2": ["h", "s", "t", "cnot", "id"]
  "3": ["h", "s", "t", "cnot", "id"]
  "4": ["h", "s", "t", "cnot", "id"]
  "5": ["h", "s", "t", "cnot", "id"]
  "6": ["h", "s", "t", "cnot", "id"]
  "7": ["h", "s", "t", "cnot", "id"]
  "8": ["h", "s", "t", "cnot", "id"]
  "9": ["h", "s", "t", "cnot", "id"]
  "10": ["h", "s", "t", "cnot", "id"]
  "11": ["h", "s", "t", "cnot", "id"]
  "12": ["h", "s", "t", "cnot", "id"]
  "13": ["h", "s", "t", "cnot", "id"]
  "14": ["h", "s", "t", "cnot", "id"]
  "15": ["h", "s", "t", "cnot", "id"]
  "16": ["h", "s", "t", "cnot", "id"]
  "17": ["h", "s", "t", "cnot", "id"]
  "18": ["h", "s", "t", "cnot", "id"]
  "19": ["h", "s", "t", "cnot", "id"]
  "20": ["h", "s", "t", "cnot", "id"]
  "21": ["h", "s", "t", "cnot", "id"]
  "22": ["h", "s", "t", "cnot", "id"]
  "23": ["h", "s", "t", "cnot", "id"]
  "24": ["h", "s", "t", "cnot", "id"]
  "25": ["h", "s", "t", "cnot", "id"]
  "26": ["h", "s", "t", "cnot", "id"]
  "27": ["h", "s", "t", "cnot", "id"]
  "28": ["h", "s", "t", "cnot", "id"]
  "29": ["h", "s", "t", "cnot", "id"]
  "30": ["h", "s", "t", "cnot", "id"]
  "31": ["h", "s", "t", "cnot", "id"]
  "32": ["h", "s", "t", "cnot", "id"]
  "33": ["h", "s", "t", "cnot", "id"]
  "34": ["h", "s", "t", "cnot", "id"]
  "35": ["h", "s", "t", "cnot", "id"]